commom: &commom
  adapter: postgresql
  encoding: utf8
  username: postgres

development:
  <<: *commom
  database: sgc_development

test:
  <<: *commom
  database: sgc_test

production:
  <<: *commom
  database: sgc_production

staging:
  <<: *commom
  database: sgc_staging